services:
  service1:
    build:
      context: ./service1
    ports:
      - "8081:8081"
    networks:
      - web

  service2:
    build:
      context: ./service2
    ports:
      - "8082:8082"
    networks:
      - web

  service3:
    build:
      context: ./service3
    ports:
      - "8083:8083"
    networks:
      - web

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
      - service3
      - prometheus
      - grafana
    networks:
      - web

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.route-prefix=/
      - --web.external-url=http://localhost/prometheus
    ports:
      - "9090:9090"
    networks:
      - web

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - web

networks:
  web:
