global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'service1'
    static_configs:
      - targets: ['service1:8081']

  - job_name: 'service2'
    static_configs:
      - targets: ['service2:8082']

  - job_name: 'service3'
    static_configs:
      - targets: ['service3:8083']

rule_files:
  - "alert.rules.yml"
